### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by jpkoff** [pixel2/jQuery-Easy-Confirm-Dialog-plugin#13]
Hello and thanks alot for this useful plugin.

Could you add in the Readme file the browser compatibility issues that you are aware of ?

I just tested the plugin on an older Mozilla : 
Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2.28) Gecko/20120306 Firefox/3.6.28
only to find out it is not working properly : the click() action is only performed if you click TWICE on the easyconfirm item, and then it displays the confirmation message for a second time.

Best regards,

Alex

**Comment by pixel2** [comment]
Thank you for your input. I have updated the plugin to support jQuery 1.8+, one of the problems previously was just like you said that that you had to click twice. Please try again with the new version, if you still have compatibility issues please come back to me.
