### ISSUE TITLE
Popup is not opening in my asp.net application

### ISSUE THREAD

**Issue by anujpratap09** [pixel2/jQuery-Easy-Confirm-Dialog-plugin#15]
Hi,

I copied all of your code of How to get started on my aspx page and added js and css reference but popup is not opening its just change the url like WebForm.aspx?confirm=true

Regards
Anuj

**Comment by pixel2** [comment]
It is really hard for me to give any help without any more information. Look at http://www.projectshadowlight.org/jquery-easy-confirm-dialog/ for working examples. If you still can't get it to work give me a URL to your code or upload a version that will reproduce your error on http://fiddle.jshell.net.

**Comment by anujpratap09** [comment]
Hi Emil,

Thanks for reply..
Popup is working now..
Thanks You..

On Mon, Nov 10, 2014 at 3:20 PM, Emil Janitzek notifications@github.com
wrote:

> It is really hard for me to give any help without any more information.
> Look at http://www.projectshadowlight.org/jquery-easy-confirm-dialog/ for
> working examples. If you still can't get it to work give me a URL to your
> code or upload a version that will reproduce your error on
> http://fiddle.jshell.net.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wiggin/jQuery-Easy-Confirm-Dialog-plugin/issues/15#issuecomment-62362090
> .

## 

Anuj Pratap Singh
