### ISSUE TITLE
No title, no dialog

### ISSUE THREAD

**Issue by FaustXVI** [pixel2/jQuery-Easy-Confirm-Dialog-plugin#2]
Hi,
I encounter a issue on firefox v3.6.20 on ubuntu 10.10 :
When I add a easyconfirm on a element with no title, the plugin crash and no dialog is shown.

I simply fix the bug by changing this line :

if ($target.attr('title').length > 0)

by this one

if ($target.attr('title') != null && $target.attr('title').length > 0)

My best,

**Comment by pixel2** [comment]
Thank you for your feedback and sorry for my late replay. I have implemented the fix as you suggested.
