### ISSUE TITLE
Bug in rebindHandlers

### ISSUE THREAD

**Issue by powerpoint** [pixel2/jQuery-Easy-Confirm-Dialog-plugin#3]
Hi,

I guess I found a bug, which only occurs if you use easyconfirm i.e. in an ajax environment , if you don't send a form and reload the part where the easyconfirm also refreshs. I changed the function rebindHandlers and corrected the target.bind which will take the handlers function not the object.

```
        // Re-bind old events
        var rebindHandlers = function() {
          if (target._handlers !== undefined) {
            jQuery.each(target._handlers,function() {
              $target.bind(type, this.handler);
            });
          }
        };
```

By the way I really appreciate this simple but nice add on.

**Comment by leolimas** [comment]
Hi,

I changed this block code on my version and it fixed mine error. Thanks a lot
