### ISSUE TITLE
Compatibility with jQueryUI button widget

### ISSUE THREAD

**Issue by alshk** [pixel2/jQuery-Easy-Confirm-Dialog-plugin#5]
I'm not sure if it's really an issue, but i suppose that since the plugin integrates well with jQuery UI it should be possible to use it with the button widget (http://jqueryui.com/demos/button/). At the moment it doesn't work for me, i get an error "((f.event.special[s.origType] || {}).handle || s.handler).apply is not a function"

To reproduce use scripts:
  https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
  https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"

And the following code (modified from examples page http://projectshadowlight.org/jquery-easy-confirm-dialog/):

``` javascript
 $(".confirm").button().easyconfirm();
                $("#alert").click(function() {
                        alert("You approved the action");
                });
```

**Comment by Vitall** [comment]
Hi I got the same error. To fix it replace 74-76 lines in plugin 

for (var i in events[type]) {
    target._handlers.push(events[type][i]);
}

with:

$.each(events[type], function(){
    target._handlers.push(this);
});

hope this will help.

**Comment by brgrz** [comment]
If possible, make a pull request, so that it gets added to the base project. Eventually. Hopefully wiggin will stop by soon.;)

**Comment by Vitall** [comment]
Done
